name: Build

on:
  push:
  schedule:
    - cron: '0 23 * * *'

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Make deb
        run: |
          python update.py
      
      - name: Github pages APT repo
        uses: jrandiny/apt-repo-action@v2.0.1
        with:
          github_token: ${{ secrets.KBCLI_GITHUB_TOKEN}}
          repo_supported_arch: | 
            arm64
            amd64
          repo_supported_version: |
            stable
          file: kbcli_arm64.deb
          file_target_version: stable
          public_key: ${{ secrets.KBCLI_APT_PUBLIC_KEY }}
          private_key: ${{ secrets.KBCLI_APT_SIGNING_KEY }}
          key_passphrase: ${{ secrets.KBCLI_APT_PASSPHRASE }}

      - name: Github pages APT repo
        uses: jrandiny/apt-repo-action@v2.0.1
        with:
          github_token: ${{ secrets.KBCLI_GITHUB_TOKEN}}
          repo_supported_arch: |
            arm64
            amd64
          repo_supported_version: |
            stable
          file: kbcli_amd64.deb
          file_target_version: stable
          public_key: ${{ secrets.KBCLI_APT_PUBLIC_KEY }}
          private_key: ${{ secrets.KBCLI_APT_SIGNING_KEY }}
          key_passphrase: ${{ secrets.KBCLI_APT_PASSPHRASE }}